# -*- coding: utf-8 -*-
"""handwritten digit recognition Farsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Icss8kBrqMXCt5BUSQa5gVwkpklUXNm9

یاسمن صفاری
برنامه ای بنویسید که اعداد دستنویس را تشخیص دهد
دیتا ست : هدی فارسی    https://farsiocr.ir/%D9%85%D8%AC%D9%85%D9%88%D8%B9%D9%87-%D8%AF%D8%A7%D8%AF%D9%87/%D9%85%D8%AC%D9%85%D9%88%D8%B9%D9%87-%D8%A7%D8%B1%D9%82%D8%A7%D9%85-%D8%AF%D8%B3%D8%AA%D9%86%D9%88%DB%8C%D8%B3-%D9%87%D8%AF%DB%8C/



مشخصات شبکه:
یک شبکه عصبی ساده با سه لایه مخفی
10 تا نورون در خروی چون ده عدد داریم
گرادیان کاهشی تصادفی آدام
لاس کراس انتروپی
"""

import scipy.io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import cv2

import keras
from keras.layers import Dense
from keras.models import Sequential

hoda = scipy.io.loadmat("/content/Data_hoda_full.mat")

data= hoda['Data'].reshape(-1)
labels = hoda['labels'].reshape(-1)
data_resized = np.array([cv2.resize(img, dsize=(5, 5)) for img in data])
data_norm = data_resized/255
data_norm = data_norm.reshape(60000,25)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_norm,labels)

n_classes = 10
y_train_cat = keras.utils.to_categorical(y_train, n_classes)
y_test_cat = keras.utils.to_categorical(y_test,n_classes)
y_train[1]





model = Sequential()

model = Sequential()
model.add(Dense(40,activation = 'sigmoid', input_shape = (25,)))
model.add(Dense(30,activation = 'sigmoid'))
model.add(Dense(40,activation = 'relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss = 'categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

model.fit(X_train,y_train_cat, batch_size = 512, epochs=100,verbose = 1)

model.evaluate(X_test,y_test_cat)
#دقت

preds = model.predict_classes(X_test)
preds
#عدد عکسای تستو برمیگردونه